### ISSUE TITLE
Forked example doesn't work?

### ISSUE THREAD

**Issue by dbackeus** [digital-fabric/tipi#8]
When running the [forked http example](https://github.com/digital-fabric/tipi/blob/master/examples/http_server_forked.rb) I only ever get responses from a single pid, so can't seem to utilize more than a single core on my machine.

System: MacOS Big Sur on a 2020 intel Macbook Pro
Ruby: 2.7.2
Tipi version: 0.33
Polyphony version: 0.47.5.1 (noticeably not the latest version, due to how the tipi dependency is configured)

**Comment by dbackeus** [comment]
Made another attempt using the HEAD version of `tipi` which uses a later version of polyphony. However still just a single ruby process responding to requests.

Also this new version appears to detach / "daemonize" the server so I can't CTRL+C to shut everything down but have to hunt the forked processes via activity monitor or similar to kill them.

I also made a fork to use the latest (0.51) version of polyphony but its behaviour was identical to tipi head.

**Comment by dbackeus** [comment]
For the record: When trying this on Ubuntu 20.10 instead of MacOS, the forked example worked nicely. So I guess this is a MacOS related issue?

**Comment by ciconia** [comment]
Most probably. I don't have access access to a Mac, so I'll appreciate any help in that regard.

**Comment by timhatch** [comment]
Hi,

I've also been working my way through the examples. Gem versions are polyphony = 0.55.0 and tipi = 0.32. I didn't specify gem versions when I ran bundler and am not sure why tipi 0.32 was installed. Anyway...

The forked example from the gem's examples folder didn't work, which I guessed was down to an obsolete call to `Polyphony::HTTP::Server.listen`. Changing that over to `Tipi.listen` fixed the issue and had the Gem's example serving across 8 forks as expected. 

The example in the GitHub repo also responds on a single fork (Big Sur on an M1 Mini) so I looked at the differences between the two examples.  The key difference appears to be where/how the server is initialised, i.e.

**Gem 0.32 Example**
```ruby
server = Tipi.listen('0.0.0.0', 1234, opts)

child_pids = []
8.times do
  pid = Polyphony.fork do
    puts "forked pid: #{Process.pid}"
    server.each do |req|
      req.respond("Hello world! from pid: #{Process.pid}\n")
    end
  rescue Interrupt
  end
  child_pids << pid
end
```
 **Github (0.38)**
```ruby
child_pids = []
8.times do  
  pid = Polyphony.fork do    
    puts "forked pid: #{Process.pid}"    
    Tipi.serve('0.0.0.0', 1234, opts) do |req|      
       req.respond("Hello world! from pid: #{Process.pid}\n")
    end
  rescue Interrupt
  end
  child_pids << pid
end
```

I haven't yet worked through the tipi source to figure out what's going on, but this may help.

**Comment by ciconia** [comment]
Thanks for reporting this. I've been doing a lot of work around Tipi in the last few month (including extracting the request/response  API into a [separate gem](https://github.com/digital-fabric/qeweney)). I'll try to update the examples so they'll work again as soon as possible.

**Comment by ciconia** [comment]
I went over all of the included examples, fixing any problems, so they should all work. Please check out version 0.39 and let me know if you find any more problems.

**Comment by timhatch** [comment]
@circonia
Super-fast getting those examples redone!

I ran through most of them, leaving aside only tests requiring a secure server (I don't have the localhost gem installed and would like to get familiar with that separately).

The following examples ran successfully straight off:
- http_server.rb
- http_server_timeout.rb
- http_server_throttled.rb
- http_server_throttled_accept.rb
- http_server_simple.rb
- http_server_graceful.rb
- http_server_form.rb
- rack_server.rb (using hello.ru as the config file)

The _routing_server.rb_ example runs though I'm not sure that r.redirect is working? If root redirects to '/hello' then I would have expected some response back.

On MacOS the _http_server_forked_ example misbehaves as previously reported. 8 forks start Modifying the code to follow the same pattern as the earlier (v0.32) example fixes the issue, much as I reported earlier, i.e.
```ruby
server = Tipi.listen('0.0.0.0', 1234, opts)

child_pids = []
8.times do
  pid = Polyphony.fork do
    puts "forked pid: #{Process.pid}"
    server.each do |req|
      req.respond("Hello world! from pid: #{Process.pid}\n")
    end
  rescue Interrupt
  end
  child_pids << pid
end
```
I haven't spent enough time with Tipi to understand the difference between the two patterns, so I'm unsure why/how this reformatting has any effect. 

For the _http_ws_server.rb_ example I needed to change the URL in _ws_page.html_ from "wss://dev.realiteq.net/" to "ws://localhost:4411" but other than that the example worked perfectly with Brave and Firefox as clients. With Safari as the client the connections errored out <Errno::ECONNRESET: Connection reset by peer - Connection reset by peer>. I'm not sure that Tipi can be blamed for differences between clients and I haven't had the time yet to explore why Safari doesn't behave, but Apple...

For the _websocket_demo.rb_ example I needed to change the requires from
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'polyphony', '~> 0.44'
  gem 'tipi', '~> 0.31'
end

require 'tipi/websocket'
```
to
```ruby
require 'bundler/setup'
require 'tipi'
require 'tipi/websocket'
```

That may be down to how I've installed Tipi (I keep "experiments" in self contained directories rather than installing the gems globally), but the example itself worked without problem.  

Nice work.

**Comment by timhatch** [comment]
Follow up to the above.
After digging around to figure out why Safari was having problems connecting, I came across this SO link:
https://stackoverflow.com/questions/62352790/websockets-not-working-on-ios-and-safari-ossstatus-error-9837

After I had enabled the `NSURLSession Websocket` feature Safari was able to connect to the _http_ws_server.rb_ example without problems from Safari. As the problem appears to be linked to TLS, I guess I'll have to check out the https/wss examples also
